// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Overclocked.Infrastructure.Persistence;

#nullable disable

namespace Overclocked.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Overclocked.Domain.BrandAggregate.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Brands", (string)null);
                });

            modelBuilder.Entity("Overclocked.Domain.CartAggregate.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts", (string)null);
                });

            modelBuilder.Entity("Overclocked.Domain.CategoryAggregate.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("Overclocked.Domain.EmployeeActivityLogAggregate.EmployeeActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeActivityLogs", (string)null);
                });

            modelBuilder.Entity("Overclocked.Domain.PermissionAggregate.Permission", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ManageUsers"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ManageRolePermissions"
                        },
                        new
                        {
                            Id = 3,
                            Name = "DeactivateUsers"
                        },
                        new
                        {
                            Id = 4,
                            Name = "ManageOrders"
                        },
                        new
                        {
                            Id = 5,
                            Name = "ManageShipments"
                        },
                        new
                        {
                            Id = 6,
                            Name = "ManagePayments"
                        },
                        new
                        {
                            Id = 7,
                            Name = "SeeStatistics"
                        },
                        new
                        {
                            Id = 8,
                            Name = "CreateReports"
                        },
                        new
                        {
                            Id = 9,
                            Name = "ManageReviews"
                        },
                        new
                        {
                            Id = 10,
                            Name = "ReplyToReview"
                        },
                        new
                        {
                            Id = 11,
                            Name = "RefundOrder"
                        },
                        new
                        {
                            Id = 12,
                            Name = "AddEditDelete"
                        });
                });

            modelBuilder.Entity("Overclocked.Domain.ProductAggregate.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.ComplexProperty<Dictionary<string, object>>("Discount", "Overclocked.Domain.ProductAggregate.Product.Discount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(2,2)")
                                .HasColumnName("Discount");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Price", "Overclocked.Domain.ProductAggregate.Product.Price#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(8,2)")
                                .HasColumnName("Price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("varchar(5)")
                                .HasColumnName("Currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Overclocked.Domain.ReviewAggregate.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("Rating");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews", (string)null);
                });

            modelBuilder.Entity("Overclocked.Domain.RoleAggregate.Role", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "DataEntry"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Customer"
                        });
                });

            modelBuilder.Entity("Overclocked.Domain.TagAggregate.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("Overclocked.Domain.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Overclocked.Domain.WishlistAggregate.Wishlist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wishlists", (string)null);
                });

            modelBuilder.Entity("Overclocked.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc", "OccurredOnUtc");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Overclocked.Domain.CartAggregate.Cart", b =>
                {
                    b.HasOne("Overclocked.Domain.UserAggregate.User", null)
                        .WithOne()
                        .HasForeignKey("Overclocked.Domain.CartAggregate.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Overclocked.Domain.CartAggregate.Entities.CartItem", "CartItems", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CartId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamptz");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamptz");

                            b1.HasKey("Id");

                            b1.HasIndex("CartId");

                            b1.ToTable("CartItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CartId");
                        });

                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("Overclocked.Domain.EmployeeActivityLogAggregate.EmployeeActivityLog", b =>
                {
                    b.HasOne("Overclocked.Domain.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Overclocked.Domain.ProductAggregate.Product", b =>
                {
                    b.HasOne("Overclocked.Domain.BrandAggregate.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Overclocked.Domain.CategoryAggregate.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Overclocked.Domain.ProductAggregate.Entities.ProductImage", "Images", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamptz");

                            b1.Property<string>("ImageUrl")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("ProductId");

                            b1.ToTable("ProductImages", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsMany("Overclocked.Domain.ProductAggregate.Entities.Specification", "Specifications", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamptz");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("NormalizedName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamptz");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)");

                            b1.HasKey("Id");

                            b1.HasIndex("ProductId");

                            b1.ToTable("ProductSpecifications", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("Overclocked.Domain.ProductAggregate.ValueObjects.ProductRating", "ProductRating", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ReviewCount")
                                .HasColumnType("integer")
                                .HasColumnName("ReviewCount");

                            b1.Property<int>("TotalScore")
                                .HasColumnType("integer")
                                .HasColumnName("TotalScore");

                            b1.HasKey("ProductId");

                            b1.HasIndex("ReviewCount");

                            b1.HasIndex("TotalScore");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsMany("Overclocked.Domain.ProductAggregate.ValueObjects.ProductTag", "Tags", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("TagId")
                                .HasColumnType("uuid")
                                .HasColumnName("TagId");

                            b1.HasKey("ProductId", "TagId");

                            b1.HasIndex("TagId");

                            b1.ToTable("ProductTags", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProductId");

                            b1.HasOne("Overclocked.Domain.TagAggregate.Tag", "Tag")
                                .WithMany()
                                .HasForeignKey("TagId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.Navigation("Tag");
                        });

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Images");

                    b.Navigation("ProductRating")
                        .IsRequired();

                    b.Navigation("Specifications");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Overclocked.Domain.ReviewAggregate.Review", b =>
                {
                    b.HasOne("Overclocked.Domain.ProductAggregate.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Overclocked.Domain.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.OwnsOne("Overclocked.Domain.ReviewAggregate.Entities.ReviewReply", "ReviewReply", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamptz");

                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Reply")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<Guid>("ReviewId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamptz");

                            b1.HasKey("Id");

                            b1.HasIndex("EmployeeId");

                            b1.HasIndex("ReviewId")
                                .IsUnique();

                            b1.ToTable("ReviewReplies", (string)null);

                            b1.HasOne("Overclocked.Domain.UserAggregate.User", null)
                                .WithMany()
                                .HasForeignKey("EmployeeId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("ReviewId");
                        });

                    b.Navigation("ReviewReply");
                });

            modelBuilder.Entity("Overclocked.Domain.RoleAggregate.Role", b =>
                {
                    b.OwnsMany("Overclocked.Domain.RoleAggregate.ValueObjects.RolePermission", "RolePermissions", b1 =>
                        {
                            b1.Property<int>("RoleId")
                                .HasColumnType("integer")
                                .HasColumnName("RoleId");

                            b1.Property<int>("PermissionId")
                                .HasColumnType("integer")
                                .HasColumnName("PermissionId");

                            b1.HasKey("RoleId", "PermissionId");

                            b1.HasIndex("PermissionId");

                            b1.ToTable("RolePermissions", (string)null);

                            b1.HasOne("Overclocked.Domain.PermissionAggregate.Permission", null)
                                .WithMany()
                                .HasForeignKey("PermissionId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("RoleId");

                            b1.HasData(
                                new
                                {
                                    RoleId = 1,
                                    PermissionId = 1
                                },
                                new
                                {
                                    RoleId = 1,
                                    PermissionId = 2
                                },
                                new
                                {
                                    RoleId = 1,
                                    PermissionId = 3
                                },
                                new
                                {
                                    RoleId = 1,
                                    PermissionId = 4
                                },
                                new
                                {
                                    RoleId = 1,
                                    PermissionId = 5
                                },
                                new
                                {
                                    RoleId = 1,
                                    PermissionId = 6
                                },
                                new
                                {
                                    RoleId = 1,
                                    PermissionId = 7
                                },
                                new
                                {
                                    RoleId = 1,
                                    PermissionId = 8
                                },
                                new
                                {
                                    RoleId = 1,
                                    PermissionId = 9
                                },
                                new
                                {
                                    RoleId = 1,
                                    PermissionId = 10
                                },
                                new
                                {
                                    RoleId = 1,
                                    PermissionId = 11
                                },
                                new
                                {
                                    RoleId = 1,
                                    PermissionId = 12
                                },
                                new
                                {
                                    RoleId = 2,
                                    PermissionId = 4
                                },
                                new
                                {
                                    RoleId = 2,
                                    PermissionId = 5
                                },
                                new
                                {
                                    RoleId = 2,
                                    PermissionId = 6
                                },
                                new
                                {
                                    RoleId = 2,
                                    PermissionId = 7
                                },
                                new
                                {
                                    RoleId = 2,
                                    PermissionId = 8
                                },
                                new
                                {
                                    RoleId = 2,
                                    PermissionId = 9
                                },
                                new
                                {
                                    RoleId = 2,
                                    PermissionId = 10
                                },
                                new
                                {
                                    RoleId = 2,
                                    PermissionId = 11
                                },
                                new
                                {
                                    RoleId = 2,
                                    PermissionId = 12
                                },
                                new
                                {
                                    RoleId = 3,
                                    PermissionId = 12
                                });
                        });

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Overclocked.Domain.UserAggregate.User", b =>
                {
                    b.HasOne("Overclocked.Domain.RoleAggregate.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Overclocked.Domain.UserAggregate.Entities.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamptz");

                            b1.Property<string>("DeviceId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime>("ExpiredAt")
                                .HasColumnType("timestamptz");

                            b1.Property<string>("TokenHash")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamptz");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("DeviceId")
                                .IsUnique();

                            b1.HasIndex("UserId");

                            b1.ToTable("RefreshTokens", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsMany("Overclocked.Domain.UserAggregate.ValueObjects.Address", "Addresses", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("City");

                            b1.HasIndex("UserId");

                            b1.ToTable("Addresses", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Overclocked.Domain.UserAggregate.ValueObjects.EmailConfirmationCode", "EmailConfirmationCode", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CodeHash")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime>("ExpiredAt")
                                .HasColumnType("timestamptz");

                            b1.Property<bool>("IsUsed")
                                .HasColumnType("boolean");

                            b1.HasKey("UserId");

                            b1.ToTable("EmailConfirmationCodes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Addresses");

                    b.Navigation("EmailConfirmationCode")
                        .IsRequired();

                    b.Navigation("RefreshTokens");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Overclocked.Domain.WishlistAggregate.Wishlist", b =>
                {
                    b.HasOne("Overclocked.Domain.UserAggregate.User", null)
                        .WithOne()
                        .HasForeignKey("Overclocked.Domain.WishlistAggregate.Wishlist", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Overclocked.Domain.WishlistAggregate.ValueObjects.WishlistItem", "WishlistItems", b1 =>
                        {
                            b1.Property<Guid>("WishlistId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid")
                                .HasColumnName("ProductId");

                            b1.HasKey("WishlistId", "ProductId");

                            b1.HasIndex("ProductId");

                            b1.ToTable("WishlistItems", (string)null);

                            b1.HasOne("Overclocked.Domain.ProductAggregate.Product", null)
                                .WithMany()
                                .HasForeignKey("ProductId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("WishlistId");
                        });

                    b.Navigation("WishlistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
