<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <!-- <PackageReference Include="Microsoft.AspNetCore.Http" /> -->
        <PackageReference Include="Scrutor" />
        <PackageReference Include="Serilog" />
        <PackageReference Include="Hangfire.AspNetCore" />
        <PackageReference Include="Hangfire.PostgreSql" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Overclocked.Domain\Overclocked.Domain.csproj" />
        <ProjectReference Include="..\Overclocked.Contracts\Overclocked.Contracts.csproj" />
    </ItemGroup>
</Project>
